[phases.setup]
nixPkgs = ["python313", "gcc"]
cmds = ["pip install -r requirements.txt", "g++ main.cpp -o huffman_engine", "chmod +x huffman_engine"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []



[start]
cmd = "gunicorn --bind 0.0.0.0:${PORT:-8080} main:app"
